# Generated by Django 3.1.2 on 2020-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tradepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, verbose_name='交易对')),
                ('fundRate', models.FloatField(verbose_name='资费')),
                ('buySpread', models.FloatField(verbose_name='买入价差')),
                ('sellSpread', models.FloatField(verbose_name='卖出价差')),
            ],
        ),
    ]
