# Generated by Django 3.1.2 on 2020-10-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tradepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, verbose_name='交易对')),
                ('futureprice', models.FloatField(verbose_name='合约价格')),
                ('spotprice', models.FloatField(verbose_name='现货价格')),
                ('exchange', models.CharField(max_length=100, verbose_name='交易所')),
                ('LastRate', models.FloatField(verbose_name='上期资费(%)')),
                ('fundRate', models.FloatField(verbose_name='本期资费(%)')),
                ('sellSpread', models.FloatField(verbose_name='合约做空盈亏(%)')),
                ('buySpread', models.FloatField(verbose_name='合约做多盈亏(%)')),
            ],
        ),
    ]
